export default {
  login: "dabinderudhan",
  id: 66643865,
  node_id: "MDQ6VXNlcjY2NjQzODY1",
  avatar_url: "https://avatars.githubusercontent.com/u/66643865?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/dabinderudhan",
  html_url: "https://github.com/dabinderudhan",
  followers_url: "https://api.github.com/users/dabinderudhan/followers",
  following_url:
    "https://api.github.com/users/dabinderudhan/following{/other_user}",
  gists_url: "https://api.github.com/users/dabinderudhan/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/dabinderudhan/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/dabinderudhan/subscriptions",
  organizations_url: "https://api.github.com/users/dabinderudhan/orgs",
  repos_url: "https://api.github.com/users/dabinderudhan/repos",
  events_url: "https://api.github.com/users/dabinderudhan/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/dabinderudhan/received_events",
  type: "User",
  site_admin: false,
  name: "Dabinder Udhan",
  company: null,
  blog: "https://dabinderudhan.com",
  location: "Mumbai",
  email: null,
  hireable: true,
  bio: "Travel Industry  🛅 to Tech Industry 💻 | Junior Frontend Developer | JavaScript | React.Js",
  twitter_username: "dabinderudhan",
  public_repos: 48,
  public_gists: 0,
  followers: 12,
  following: 17,
  created_at: "2020-06-08T19:36:44Z",
  updated_at: "2022-12-12T04:20:47Z",
};
